### ISSUE TITLE
Add benchmark comparison vs @formatjs/intl-segmenter 

### ISSUE THREAD

**Issue by cheeaun** [cometkim/unicode-segmenter#41]
Would be curious to know the comparison with [@formatjs/intl-segmenter](https://formatjs.io/docs/polyfills/intl-segmenter/) — for context, I'm currently using this as a polyfill if `Intl.Segmenter` is not supported.

**Comment by cometkim** [comment]
@cheeaun updated results :)

It looks `@formatjs/intl-segmenter` would be nice option in general. But if you only want grapheme it might be too heavy.

**Comment by cheeaun** [comment]
@cometkim thanks! This is very helpful 🙇‍♂️
